=== qiq/hector_core/hector_config.dtd
<!-- hector config definition -->

<!ELEMENT Config	(Server+) >

<!-- common elements -->

<!ELEMENT param		EMPTY >
<!ATTLIST param
	name		CDATA		""
	value		CDATA		"" >

<!ELEMENT lib		EMPTY >
<!ATTLIST lib
	name		CDATA		#REQUIRED
	type		CDATA		"" >

<!ELEMENT threads	(#PCDATA) >

<!-- Main -->

<!ELEMENT Binary	(path|arg|env)* >
<!ATTLIST Binary
	id		ID		#REQUIRED >
<!ELEMENT path		(#PCDATA) >
<!ELEMENT arg		(#PCDATA) >
<!ELEMENT env		(#PCDATA) >


<!ELEMENT Server	(threads|serverHost|serverPort|ProcessingEngine|param|logConfig)* >
<!ATTLIST Server
	id		ID		#REQUIRED
	lib		CDATA		#REQUIRED >
<!ELEMENT serverHost	(#PCDATA) >
<!ELEMENT serverPort	(#PCDATA) >
<!ELEMENT logConfig	(#PCDATA) >

<!-- ProcessingEngine -->

<!ELEMENT ProcessingEngine	(Processor+) >
<!ATTLIST ProcessingEngine
	id		ID		#REQUIRED>

<!-- Processor -->

<!ELEMENT Processor	(threads,modules,input?,output?) >
<!ATTLIST Processor
	id		ID		#REQUIRED >

<!ELEMENT modules	(Module+) >

<!ELEMENT input		(queue+) >

<!ELEMENT output	(nextProcessor+) >

<!ELEMENT queue	EMPTY >
<!ATTLIST queue
	priority	CDATA		"0"
	maxItems	CDATA		"0"
	maxSize		CDATA		"0" >

<!ELEMENT nextProcessor	EMPTY >
<!ATTLIST nextProcessor
	ref		IDREF 		#REQUIRED
	priority	CDATA		"0"
	filter		CDATA		""
	copy		CDATA		"0" >

<!-- Module -->

<!ELEMENT Module	(param*) >
<!ATTLIST Module
	id		ID		#REQUIRED
	lib		CDATA		#REQUIRED
	type		CDATA		"native" >

=== qiq/hector_core/test/test17_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test7: copy of a resource: one reader(1), one simple module(1), two writers(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig><![CDATA[
			log4j.rootLogger=DEBUG, LOGFILE
			log4j.appender.LOGFILE=org.apache.log4j.FileAppender
			log4j.appender.LOGFILE.File=test.log
			log4j.appender.LOGFILE.Append=true
			log4j.appender.LOGFILE.Threshold=DEBUG
			log4j.appender.LOGFILE.layout=org.apache.log4j.PatternLayout
			log4j.appender.LOGFILE.layout.ConversionPattern=%m%n ]]>
		</logConfig>
		<resources>
			<Resource id="R_test" lib="TestResource.la"/>
		</resources>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" type="perl" lib="TestInput.pm">
						<param name="maxItems" value="1000"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_output1" copy="1"/>
					<nextProcessor ref="P_output2"/>
				</output>
			</Processor>
			<Processor id="P_output1">
				<threads>1</threads>
				<modules>
					<Module id="M_output1" type="perl" lib="TestOutput.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
			<Processor id="P_output2">
				<threads>1</threads>
				<modules>
					<Module id="M_output2" type="perl" lib="TestOutput.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test24-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test4: multithreaded intermediate (simple): reader(5), one simple intermediate(5), one writer(5)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig>test.log.props</logConfig>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>5</threads>
				<modules>
					<Module id="M_input" type="python" lib="TestInput.py">
						<param name="maxItems" value="1000"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_simple"/>
				</output>
			</Processor>
			<Processor id="P_simple">
				<threads>5</threads>
				<modules>
					<Module id="M_simple" type="python" lib="TestSimple.py"/>
				</modules>
				<input>
					<queue/>
				</input>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>5</threads>
				<modules>
					<Module id="M_output" type="python" lib="TestOutput.py"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/load_save.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
load_save: test of loading/saving module
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig><![CDATA[
			log4j.rootLogger=DEBUG, LOGFILE
			log4j.appender.LOGFILE=org.apache.log4j.FileAppender
			log4j.appender.LOGFILE.File=load_save.log
			log4j.appender.LOGFILE.Append=false
			log4j.appender.LOGFILE.Threshold=DEBUG
			log4j.appender.LOGFILE.layout=org.apache.log4j.PatternLayout
			log4j.appender.LOGFILE.layout.ConversionPattern=%m%n ]]>
		</logConfig>
		<ProcessingEngine id="PE_test">
			<Processor id="P_load">
				<threads>1</threads>
				<modules>
					<Module id="M_load" lib="Load.la">
						<param name="filename" value="$1"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_save"/>
				</output>
			</Processor>
			<Processor id="P_save">
				<threads>1</threads>
				<modules>
					<Module id="M_save" lib="Save.la">
						<param name="filename" value="$2"/>
						<param name="saveResourceType" value="true"/>
					</Module>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test9-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test9: multiple module: one reader(1), one multi intermediate(1), one writer(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1100</serverPort>
		<logConfig>test.log.props</logConfig>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" lib="TestInput.la">
						<param name="maxItems" value="100"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_multi"/>
				</output>
			</Processor>
			<Processor id="P_multi">
				<threads>1</threads>
				<modules>
					<Module id="M_dump1" lib="Dump.la"/>
					<Module id="M_multi1" lib="TestMulti.la">
						<param name="timeTick" value="100"/>
					</Module>
					<Module id="m_dump2" lib="Dump.la"/>
					<Module id="M_multi2" lib="TestMulti.la">
						<param name="timeTick" value="100"/>
					</Module>
					<Module id="M_dump3" lib="Dump.la"/>
				</modules>
				<input>
					<queue/>
				</input>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>1</threads>
				<modules>
					<Module id="M_dump4" lib="Dump.la"/>
					<Module id="M_output" lib="TestOutput.la"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test10_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test10: test of loading/saving module
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig>test.log.props</logConfig>
		<resources>
			<Resource id="R_test" lib="TestResource.la"/>
		</resources>
		<ProcessingEngine id="PE_test">
			<Processor id="P_load">
				<threads>1</threads>
				<modules>
					<Module id="M_load" lib="Load.la">
						<param name="filename" value="test10.data.in"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_save"/>
				</output>
			</Processor>
			<Processor id="P_save">
				<threads>1</threads>
				<modules>
					<Module id="M_save" lib="Save.la">
						<param name="filename" value="test10.data.out"/>
					</Module>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test17-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test7: copy of a resource: one reader(1), one simple module(1), two writers(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1100</serverPort>
		<logConfig>test.log.props</logConfig>
		<ProcessingEngine id="robot_processing_engine">
			<Processor id="P_load_resource">
				<threads>1</threads>
				<modules>
					<Module id="M_load_resource" type="perl" lib="TestInput.pm">
						<param name="maxItems" value="1000"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_save_resource1" copy="1"/>
					<nextProcessor ref="P_save_resource2"/>
				</output>
			</Processor>
			<Processor id="P_save_resource1">
				<threads>1</threads>
				<modules>
					<Module id="M_save_resource1" type="perl" lib="TestOutput.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
			<Processor id="P_save_resource2">
				<threads>1</threads>
				<modules>
					<Module id="M_save_resource2" type="perl" lib="TestOutput.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/input_multi_output.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
input_multi_output: multiple module: one reader(1), one multi intermediate(1), one writer(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig><![CDATA[
			log4j.rootLogger=DEBUG, LOGFILE
			log4j.appender.LOGFILE=org.apache.log4j.FileAppender
			log4j.appender.LOGFILE.File=input_multi_output.log
			log4j.appender.LOGFILE.Append=false
			log4j.appender.LOGFILE.Threshold=DEBUG
			log4j.appender.LOGFILE.layout=org.apache.log4j.PatternLayout
			log4j.appender.LOGFILE.layout.ConversionPattern=%m%n ]]>
		</logConfig>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" lib="TestInput.la">
						<param name="maxItems" value="100"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_multi"/>
				</output>
			</Processor>
			<Processor id="P_multi">
				<threads>1</threads>
				<modules>
					<Module id="M_dump1" lib="Dump.la"/>
					<Module id="M_multi1" lib="TestMulti.la">
						<param name="timeTick" value="100"/>
					</Module>
					<Module id="m_dump2" lib="Dump.la"/>
					<Module id="M_multi2" lib="TestMulti.la">
						<param name="timeTick" value="100"/>
					</Module>
					<Module id="M_dump3" lib="Dump.la"/>
				</modules>
				<input>
					<queue/>
				</input>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>1</threads>
				<modules>
					<Module id="M_dump4" lib="Dump.la"/>
					<Module id="M_output" lib="TestOutput.la"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/misc/convert.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
Convert resource files from/to text format.
-->
<Config>
	<Server id="convert" lib="TestServer.la">
		<threads>2</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig><![CDATA[
			log4j.rootLogger=ERROR, LOG
			log4j.appender.LOG=org.apache.log4j.ConsoleAppender
			log4j.appender.LOG.Target=System.err
			log4j.appender.LOG.Threshold=DEBUG
			log4j.appender.LOG.layout=org.apache.log4j.PatternLayout
			log4j.appender.LOG.layout.ConversionPattern=%m%n ]]>
		</logConfig>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_load" lib="Load.la">
						<param name="filename" value="$1"/>
						<param name="text" value="$2"/>
						<param name="resourceType" value="$3"/>
					</Module>
					<Module id="M_save" lib="Save.la">
						<param name="filename" value="$4"/>
						<param name="text" value="$5"/>
						<param name="saveResourceType" value="$6"/>
						<param name="saveResourceIdStatus" value="$7"/>
					</Module>
				</modules>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>
