=== qiq/hector_core/hector_config.dtd
<!-- hector config definition -->

<!ELEMENT Config	(Server+) >

<!-- common elements -->

<!ELEMENT param		EMPTY >
<!ATTLIST param
	name		CDATA		""
	value		CDATA		"" >

<!ELEMENT lib		EMPTY >
<!ATTLIST lib
	name		CDATA		#REQUIRED
	type		CDATA		"" >

<!ELEMENT threads	(#PCDATA) >

<!-- Main -->

<!ELEMENT Binary	(path|arg|env)* >
<!ATTLIST Binary
	id		ID		#REQUIRED >
<!ELEMENT path		(#PCDATA) >
<!ELEMENT arg		(#PCDATA) >
<!ELEMENT env		(#PCDATA) >


<!ELEMENT Server	(threads|serverHost|serverPort|ProcessingEngine|param|logConfig)* >
<!ATTLIST Server
	id		ID		#REQUIRED
	lib		CDATA		#REQUIRED >
<!ELEMENT serverHost	(#PCDATA) >
<!ELEMENT serverPort	(#PCDATA) >
<!ELEMENT logConfig	(#PCDATA) >

<!-- ProcessingEngine -->

<!ELEMENT ProcessingEngine	(Processor+) >
<!ATTLIST ProcessingEngine
	id		ID		#REQUIRED>

<!-- Processor -->

<!ELEMENT Processor	(threads,modules,input?,output?) >
<!ATTLIST Processor
	id		ID		#REQUIRED >

<!ELEMENT modules	(Module+) >

<!ELEMENT input		(queue+) >

<!ELEMENT output	(nextProcessor+) >

<!ELEMENT queue	EMPTY >
<!ATTLIST queue
	priority	CDATA		"0"
	maxItems	CDATA		"0"
	maxSize		CDATA		"0" >

<!ELEMENT nextProcessor	EMPTY >
<!ATTLIST nextProcessor
	ref		IDREF 		#REQUIRED
	priority	CDATA		"0"
	filter		CDATA		""
	copy		CDATA		"0" >

<!-- Module -->

<!ELEMENT Module	(param*) >
<!ATTLIST Module
	id		ID		#REQUIRED
	lib		CDATA		#REQUIRED
	type		CDATA		"native" >

=== qiq/hector_core/test/input_multi_output_pl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
input_multi_output_pl: multiple module: one reader(1), one multi intermediate(1), one writer(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig><![CDATA[
			log4j.rootLogger=DEBUG, LOGFILE
			log4j.appender.LOGFILE=org.apache.log4j.FileAppender
			log4j.appender.LOGFILE.File=input_multi_output_pl.log
			log4j.appender.LOGFILE.Append=false
			log4j.appender.LOGFILE.Threshold=DEBUG
			log4j.appender.LOGFILE.layout=org.apache.log4j.PatternLayout
			log4j.appender.LOGFILE.layout.ConversionPattern=%m%n ]]>
		</logConfig>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" type="perl" lib="TestInput.pm">
						<param name="maxItems" value="100"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_multi"/>
				</output>
			</Processor>
			<Processor id="P_multi">
				<threads>1</threads>
				<modules>
					<Module id="M_dump1" type="perl" lib="Dump.pm"/>
					<Module id="M_multi1" type="perl" lib="TestMulti.pm"/>
					<Module id="M_dump2" type="perl" lib="Dump.pm"/>
					<Module id="M_multi2" type="perl" lib="TestMulti.pm"/>
					<Module id="M_dump3" type="perl" lib="Dump.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>1</threads>
				<modules>
					<Module id="M_dump4" type="perl" lib="Dump.pm"/>
					<Module id="M_output" type="perl" lib="TestOutput.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test11_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test11: read-write: one reader(1), one writer(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig><![CDATA[
			log4j.rootLogger=DEBUG, LOGFILE
			log4j.appender.LOGFILE=org.apache.log4j.FileAppender
			log4j.appender.LOGFILE.File=test11.log
			log4j.appender.LOGFILE.Append=false
			log4j.appender.LOGFILE.Threshold=DEBUG
			log4j.appender.LOGFILE.layout=org.apache.log4j.PatternLayout
			log4j.appender.LOGFILE.layout.ConversionPattern=%m%n ]]>
		</logConfig>
		<resources>
			<Resource id="R_test" lib="TestResource.la"/>
		</resources>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" type="perl" lib="TestInput.pm">
						<param name="maxItems" value="1000"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>1</threads>
				<modules>
					<Module id="M_output" type="perl" lib="TestOutput.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test11-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test1: read-write: one reader(1), one writer(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1100</serverPort>
		<logConfig>test.log.props</logConfig>
		<ProcessingEngine id="test_processing_engine">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" type="perl" lib="TestInput.pm">
						<param name="maxItems" value="1000"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>1</threads>
				<modules>
					<Module id="M_output" type="perl" lib="TestOutput.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test5_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test5: two readers(1), one simple intermediates(1), one writer(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig><![CDATA[
			log4j.rootLogger=DEBUG, LOGFILE
			log4j.appender.LOGFILE=org.apache.log4j.FileAppender
			log4j.appender.LOGFILE.File=test.log
			log4j.appender.LOGFILE.Append=true
			log4j.appender.LOGFILE.Threshold=DEBUG
			log4j.appender.LOGFILE.layout=org.apache.log4j.PatternLayout
			log4j.appender.LOGFILE.layout.ConversionPattern=%m%n ]]>
		</logConfig>
		<resources>
			<Resource id="R_test" lib="TestResource.la"/>
		</resources>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input1">
				<threads>1</threads>
				<modules>
					<Module id="M_input1" lib="TestInput.la">
						<param name="maxItems" value="1000"/>
						<param name="idPrefix" value="i1-"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_simple"/>
				</output>
			</Processor>
			<Processor id="P_input2">
				<threads>1</threads>
				<modules>
					<Module id="M_input2" lib="TestInput.la">
						<param name="maxItems" value="2000"/>
						<param name="idPrefix" value="i2-"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_simple"/>
				</output>
			</Processor>
			<Processor id="P_simple">
				<threads>5</threads>
				<modules>
					<Module id="M_simple" lib="TestSimple.la"/>
				</modules>
				<input>
					<queue/>
				</input>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>1</threads>
				<modules>
					<Module id="M_output" lib="TestOutput.la"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test10-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test10: test of loading/saving module
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1100</serverPort>
		<logConfig>test.log.props</logConfig>
		<ProcessingEngine id="test_processing_engine">
			<Processor id="P_load">
				<threads>1</threads>
				<modules>
					<Module id="M_load" lib="LoadResource.la">
						<param name="filename" value="test10.data.in"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_save"/>
				</output>
			</Processor>
			<Processor id="P_save">
				<threads>1</threads>
				<modules>
					<Module id="M_save" lib="SaveResource.la">
						<param name="filename" value="test10.data.out"/>
					</Module>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test14_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test4: multithreaded intermediate (simple): reader(5), one simple intermediate(5), one writer(5)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig>test.log.props</logConfig>
		<resources>
			<Resource id="R_test" lib="TestResource.la"/>
		</resources>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>5</threads>
				<modules>
					<Module id="M_input" type="perl" lib="TestInput.pm">
						<param name="maxItems" value="1000"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_simple"/>
				</output>
			</Processor>
			<Processor id="P_simple">
				<threads>5</threads>
				<modules>
					<Module id="M_simple" type="perl" lib="TestSimple.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>5</threads>
				<modules>
					<Module id="M_output" type="perl" lib="TestOutput.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test19-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test9: multiple module: one reader(1), one multi intermediate(1), one writer(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1100</serverPort>
		<logConfig>test.log.props</logConfig>
		<ProcessingEngine id="test_processing_engine">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" type="perl" lib="TestInput.pm">
						<param name="maxItems" value="1000"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_multi"/>
				</output>
			</Processor>
			<Processor id="P_multi">
				<threads>1</threads>
				<modules>
					<Module id="M_dump1" type="perl" lib="Dump.pm"/>
					<Module id="M_multi1" type="perl" lib="TestMulti.pm"/>
					<Module id="M_dump2" type="perl" lib="Dump.pm"/>
					<Module id="M_multi2" type="perl" lib="TestMulti.pm"/>
					<Module id="M_dump3" type="perl" lib="Dump.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>1</threads>
				<modules>
					<Module id="M_dump4" type="perl" lib="Dump.pm"/>
					<Module id="M_output" type="perl" lib="TestOutput.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/input_simple_output_mt_py.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
input_simple_output_mt_py: multithreaded intermediate (simple): reader(5), one simple intermediate(5), one writer(5)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig><![CDATA[
			log4j.rootLogger=DEBUG, LOGFILE
			log4j.appender.LOGFILE=org.apache.log4j.FileAppender
			log4j.appender.LOGFILE.File=input_simple_output_mt_py.log
			log4j.appender.LOGFILE.Append=false
			log4j.appender.LOGFILE.Threshold=DEBUG
			log4j.appender.LOGFILE.layout=org.apache.log4j.PatternLayout
			log4j.appender.LOGFILE.layout.ConversionPattern=%m%n ]]>
		</logConfig>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>5</threads>
				<modules>
					<Module id="M_input" type="python" lib="TestInput.py">
						<param name="maxItems" value="1000"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_simple"/>
				</output>
			</Processor>
			<Processor id="P_simple">
				<threads>5</threads>
				<modules>
					<Module id="M_simple" type="python" lib="TestSimple.py"/>
				</modules>
				<input>
					<queue/>
				</input>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>5</threads>
				<modules>
					<Module id="M_output" type="python" lib="TestOutput.py"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>
