=== qiq/hector_core/hector_config.dtd
<!-- hector config definition -->

<!ELEMENT Config	(Server+) >

<!-- common elements -->

<!ELEMENT param		EMPTY >
<!ATTLIST param
	name		CDATA		""
	value		CDATA		"" >

<!ELEMENT lib		EMPTY >
<!ATTLIST lib
	name		CDATA		#REQUIRED
	type		CDATA		"" >

<!ELEMENT threads	(#PCDATA) >

<!-- Main -->

<!ELEMENT Binary	(path|arg|env)* >
<!ATTLIST Binary
	id		ID		#REQUIRED >
<!ELEMENT path		(#PCDATA) >
<!ELEMENT arg		(#PCDATA) >
<!ELEMENT env		(#PCDATA) >


<!ELEMENT Server	(threads|serverHost|serverPort|ProcessingEngine|param|logConfig)* >
<!ATTLIST Server
	id		ID		#REQUIRED
	lib		CDATA		#REQUIRED >
<!ELEMENT serverHost	(#PCDATA) >
<!ELEMENT serverPort	(#PCDATA) >
<!ELEMENT logConfig	(#PCDATA) >

<!-- ProcessingEngine -->

<!ELEMENT ProcessingEngine	(Processor+) >
<!ATTLIST ProcessingEngine
	id		ID		#REQUIRED>

<!-- Processor -->

<!ELEMENT Processor	(threads,modules,input?,output?) >
<!ATTLIST Processor
	id		ID		#REQUIRED >

<!ELEMENT modules	(Module+) >

<!ELEMENT input		(queue+) >

<!ELEMENT output	(nextProcessor+) >

<!ELEMENT queue	EMPTY >
<!ATTLIST queue
	priority	CDATA		"0"
	maxItems	CDATA		"0"
	maxSize		CDATA		"0" >

<!ELEMENT nextProcessor	EMPTY >
<!ATTLIST nextProcessor
	ref		IDREF 		#REQUIRED
	priority	CDATA		"0"
	filter		CDATA		""
	copy		CDATA		"0" >

<!-- Module -->

<!ELEMENT Module	(param*) >
<!ATTLIST Module
	id		ID		#REQUIRED
	lib		CDATA		#REQUIRED
	type		CDATA		"native" >

=== qiq/hector_core/test/test16-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test6: sort according to status: two readers(1), connected to two intermediates(1), another simple intermediate, two writers(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1100</serverPort>
		<logConfig>test.log.props</logConfig>
		<ProcessingEngine id="robot_processing_engine">
			<Processor id="P_load_resource1">
				<threads>1</threads>
				<modules>
					<Module id="M_load_resource1" type="perl" lib="TestInput.pm">
						<param name="maxItems" value="1000"/>
						<param name="idPrefix" value="i1-"/>
					</Module>
					<Module id="M_simple1" type="perl" lib="TestSimple.pm">
						<param name="setStatus" value="1"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_simple"/>
				</output>
			</Processor>
			<Processor id="P_load_resource2">
				<threads>1</threads>
				<modules>
					<Module id="M_load_resource2" type="perl" lib="TestInput.pm">
						<param name="maxItems" value="2000"/>
						<param name="idPrefix" value="i2-"/>
					</Module>
					<Module id="M_simple2" type="perl" lib="TestSimple.pm">
						<param name="setStatus" value="0"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_simple"/>
				</output>
			</Processor>
			<Processor id="P_simple">
				<threads>1</threads>
				<modules>
					<Module id="M_simple" type="perl" lib="TestSimple.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
				<output>
					<nextProcessor ref="P_save_resource1" filter="1"/>
					<nextProcessor ref="P_save_resource2"/>
				</output>
			</Processor>
			<Processor id="P_save_resource1">
				<threads>1</threads>
				<modules>
					<Module id="M_save_resource1" type="perl" lib="TestOutput.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
			<Processor id="P_save_resource2">
				<threads>1</threads>
				<modules>
					<Module id="M_save_resource2" type="perl" lib="TestOutput.pm"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test34_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test34: read-write with TestPerl module interacting with TestPerlResource
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>2</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig>test.log.props</logConfig>
		<resources>
			<Resource id="R_test" type="perl" lib="TestPerlResource.pm"/>
		</resources>
		<ProcessingEngine id="PE_test">
			<Processor id="P_test">
				<threads>1</threads>
				<modules>
					<Module id="M_input" lib="TestInput.la">
						<param name="maxItems" value="1000"/>
						<param name="resourceType" value="TestPerlResource"/>
					</Module>
					<Module id="M_test" type="perl" lib="TestPerl.pm"/>
					<Module id="M_output" lib="TestOutput.la"/>
				</modules>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test27_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test7: copy of a resource: one reader(1), one simple module(1), two writers(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig>test.log.props</logConfig>
		<resources>
			<Resource id="R_test" lib="TestResource.la"/>
		</resources>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" type="python" lib="TestInput.py">
						<param name="maxItems" value="1000"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_output1" copy="1"/>
					<nextProcessor ref="P_output2"/>
				</output>
			</Processor>
			<Processor id="P_output1">
				<threads>1</threads>
				<modules>
					<Module id="M_output1" type="python" lib="TestOutput.py"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
			<Processor id="P_output2">
				<threads>1</threads>
				<modules>
					<Module id="M_output2" type="python" lib="TestOutput.py"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test7-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test7: copy of a resource: one reader(1), one simple module(1), two writers(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1100</serverPort>
		<logConfig>test.log.props</logConfig>
		<ProcessingEngine id="test_processing_engine">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" lib="TestInput.la">
						<param name="maxItems" value="1000"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_output1" copy="1"/>
					<nextProcessor ref="P_output2"/>
				</output>
			</Processor>
			<Processor id="P_output1">
				<threads>1</threads>
				<modules>
					<Module id="M_output1" lib="TestOutput.la"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
			<Processor id="P_output2">
				<threads>1</threads>
				<modules>
					<Module id="M_output2" lib="TestOutput.la"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test33_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test33: read-write: one reader(1), one writer(1), using TestPerlResource
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>2</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig>test.log.props</logConfig>
		<resources>
			<Resource id="R_test" type="perl" lib="TestPerlResource.pm"/>
		</resources>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" lib="TestInput.la">
						<param name="maxItems" value="1000"/>
						<param name="resourceType" value="TestPerlResource"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>1</threads>
				<modules>
					<Module id="M_output" lib="TestOutput.la"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/load_save_multi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
load_save_multi: test of loading/saving module using multi type
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig><![CDATA[
			log4j.rootLogger=DEBUG, LOGFILE
			log4j.appender.LOGFILE=org.apache.log4j.FileAppender
			log4j.appender.LOGFILE.File=load_save_multi.log
			log4j.appender.LOGFILE.Append=false
			log4j.appender.LOGFILE.Threshold=DEBUG
			log4j.appender.LOGFILE.layout=org.apache.log4j.PatternLayout
			log4j.appender.LOGFILE.layout.ConversionPattern=%m%n ]]>
		</logConfig>
		<ProcessingEngine id="PE_test">
			<Processor id="P_load">
				<threads>1</threads>
				<modules>
					<Module id="M_load1" lib="Load.la">
						<param name="filename" value="/dev/null"/>
						<param name="mark" value="true"/>
					</Module>
					<Module id="M_load2" lib="Load.la">
						<param name="moduleType" value="MULTI"/>
						<param name="filename" value="$1"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_save"/>
				</output>
			</Processor>
			<Processor id="P_save">
				<threads>1</threads>
				<modules>
					<Module id="M_save" lib="Save.la">
						<param name="moduleType" value="MULTI"/>
						<param name="filename" value="$2"/>
						<param name="saveResourceType" value="true"/>
						<param name="resourceTypeFilter" value="TestResource TestProtobufResource"/>
					</Module>
					<Module id="M_save2" lib="TestOutput.la"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test32_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test22: call a processing engine from within another
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig>test.log.props</logConfig>
		<resources>
			<Resource id="R_test" lib="TestResource.la"/>
		</resources>
		<ProcessingEngine id="PE_second">
			<inputProcessor ref="P_simple"/>
			<Processor id="P_simple">
				<threads>1</threads>
				<modules>
					<Module id="M_simple" lib="TestSimple.la"/>
					<Module id="M_dump2" lib="Dump.la"/>
				</modules>
				<input>
					<queue/>
				</input>
				<output>
					<nextProcessor ref="PE_second"/>
				</output>
			</Processor>
		</ProcessingEngine>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" lib="TestInput.la">
						<param name="maxItems">1000</param>
					</Module>
					<Module id="M_dump1" lib="Dump.la"/>
					<Module id="M_call" lib="TestCall.la">
						<param name="targetEngine" value="PE_second"/>
						<param name="resourceType" value="TestResource"/>
					</Module>
					<Module id="M_dump3" lib="Dump.la"/>
					<Module id="M_output" lib="TestOutput.la"/>
				</modules>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>

=== qiq/hector_core/test/test3_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "hector_config.dtd">
<!--
test3: intermediate (simple): one reader(1), one simple intermediate(1), one writer(1)
-->
<Config>
	<Server id="test" lib="TestServer.la">
		<threads>1</threads>
		<serverHost>*</serverHost>
		<serverPort>1101</serverPort>
		<logConfig>test.log.props</logConfig>
		<resources>
			<Resource id="R_test" lib="TestResource.la"/>
		</resources>
		<ProcessingEngine id="PE_test">
			<Processor id="P_input">
				<threads>1</threads>
				<modules>
					<Module id="M_input" lib="TestInput.la">
						<param name="maxItems" value="1000"/>
					</Module>
				</modules>
				<output>
					<nextProcessor ref="P_simple"/>
				</output>
			</Processor>
			<Processor id="P_simple">
				<threads>1</threads>
				<modules>
					<Module id="M_simple" lib="TestSimple.la"/>
				</modules>
				<input>
					<queue/>
				</input>
				<output>
					<nextProcessor ref="P_output"/>
				</output>
			</Processor>
			<Processor id="P_output">
				<threads>1</threads>
				<modules>
					<Module id="M_output" lib="TestOutput.la"/>
				</modules>
				<input>
					<queue/>
				</input>
			</Processor>
		</ProcessingEngine>
	</Server>
</Config>
